#!/bin/bash

CLYDE_TMP=clyde-tmp
SUDO=sudo

function clean_up () {
	rm -rf $CLYDE_TMP 
	exit
}

function build_aur_pkg () {
	PACKAGE="$1"
	URL=https://aur.archlinux.org/$PACKAGE.git
	OPTION="n"

	# Check if package exists
	if curl -s --request GET "https://aur.archlinux.org/rpc/?v=5&type=info&arg[]=$PACKAGE" | grep '"resultcount":0' > /dev/null
	then
	       echo "Package ${PACKAGE} not found"
	       exit
	else
		mkdir $CLYDE_TMP
		cd $CLYDE_TMP
		read -p "Install ${PACKAGE}? [y/N]: " $OPTION
		if [[ "$OPTION" == "n" || "$OPTION" == "N" ]]
		then
			echo "Canceled by the user! Exiting..."
			clean_up
		fi
		git clone $URL # clone
		cd $PACKAGE
		
		$EDITOR ~/$CLYDE_TMP/$PACKAGE/PKGBUILD
		makepkg -si
		
		# Clean up
		cd ~
		echo "Cleaning up..."
		clean_up
	fi
}

if [[ "${1-}" =~ ^-*h(elp)?$ ]]; then
	echo 'Usage: '
	echo "install/ins [PACKAGE]: Installs a package"
	echo "yeet/remove/rm [PACKAGE]: Removes a package"
	exit
fi

cd ~
if [[ "$1" = "install" || "$1" = "ins" ]] 
then
	build_aur_pkg "$2"
elif [[ "$1" = "yeet" || "$1" = "remove "] ||  "$1" = "rm" ]] 
then 
	$SUDO pacman -Rn $PACKAGE
else
	echo "Unreconized argument!"
fi
